# Generated by Django 4.1 on 2024-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('matric_number', models.CharField(max_length=11, verbose_name='matric_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('otp', models.IntegerField(verbose_name='otp')),
                ('loggedin', models.BooleanField(verbose_name='loggedin')),
                ('voted', models.BooleanField(verbose_name='voted')),
            ],
        ),
    ]
